#!/usr/bin/env ansible-playbook
---
- hosts: pi
  tasks:
  - name: gpiozero python libs
    become: yes
    become_method: sudo
    apt: pkg= {{ item }} state=latest
    with_items:
      - python-gpiozero
      - python3-gpiozero